# Generated by Django 4.1.2 on 2023-06-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('social_media', models.CharField(max_length=32)),
            ],
        ),
    ]
